### ISSUE TITLE
Problem with compilation of python 2.7.6 under windows

### ISSUE THREAD

**Issue by ycollet** [davidsansome/python-cmake-buildsystem#39]
I meet a problem with compilation of python 2.7.6 under windows.
Certainly due to the difference of behavior of semicolon between linux and windows.
Here is a patch which allows to compile python under windows 7 + visual 2008:

From f33adbc5c9e98fa24a14449ccb22fd071efccca1 Mon Sep 17 00:00:00 2001
From: Yann Collette <ycollette.nospam@free.fr>
Date: Wed, 7 May 2014 09:37:54 +0200
Subject: [PATCH 2/2] manage semicolon for windows compilation

---
 cmake/libpython/CMakeLists.txt | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/cmake/libpython/CMakeLists.txt b/cmake/libpython/CMakeLists.txt
index d81b268..83459d4 100644
--- a/cmake/libpython/CMakeLists.txt
+++ b/cmake/libpython/CMakeLists.txt
@@ -183,6 +183,10 @@ elseif(WIN32)
         set(PYTHONPATH "${PYTHONPATH}${PATHSEP}.\\\\${PYTHONHOME_ESCAPED}\\\\lib-tk")
     endif(ENABLE_TKINTER)
     
+    if (WIN32)
+      string(REPLACE ";" "\\;" PYTHONPATH "${PYTHONPATH}")
+    endif ()
+    
     set_property(
         SOURCE ${SRC_DIR}/PC/getpathp.c
         PROPERTY COMPILE_DEFINITIONS
-- 
1.9.0

**Comment by jcfr** [comment]
This should be fixed by 30ce6c97392c2aa0
