### ISSUE TITLE
after version 2.7.4 of python sysconfigdata need to be built at compile time

### ISSUE THREAD

**Issue by ycollet** [davidsansome/python-cmake-buildsystem#41]
after version 2.7.4 of python sysconfigdata need to be built at compile time.
Here is a patch to perform the generation of sysconfigdata.py file:

From 71c8d07c1105941e1f8f61620f32203367fc1d9a Mon Sep 17 00:00:00 2001
From: Yann Collette <ycollette.nospam@free.fr>
Date: Wed, 7 May 2014 16:36:36 +0200
Subject: [PATCH 1/1] generate sysconfigdata depending on python version

---
 cmake/python/CMakeLists.txt | 7 +++++++
 1 file changed, 7 insertions(+)

diff --git a/cmake/python/CMakeLists.txt b/cmake/python/CMakeLists.txt
index fd3cfa8..415f555 100644
--- a/cmake/python/CMakeLists.txt
+++ b/cmake/python/CMakeLists.txt
@@ -23,6 +23,13 @@ set_property(GLOBAL APPEND PROPERTY PYTHON_TARGETS python)
 install(TARGETS python EXPORT PythonTargets RUNTIME DESTINATION ${BIN_INSTALL_DIR} COMPONENT Runtime)
 
 if(UNIX)
+  if ("${PY_VERSION_MAJOR}.${PY_VERSION_MINOR}.${PY_VERSION_PATCH}" VERSION_GREATER "2.7.4")
+    add_custom_target(build_sysconfigdata ALL
+                      COMMAND $<TARGET_FILE:python> "-E" "-S" "-m" "sysconfig" "--generate-posix-vars"
+		      COMMAND find "${CMAKE_BINARY_DIR}/build" "-name" "'*.py'" "-exec" "cp" "{}" "${CMAKE_BINARY_DIR}/${PYTHONHOME}" "\;"
+                      COMMENT "Generation of sysconfigdata file")
+  endif ()
+  
   install(CODE
 "message(STATUS \"Creating Python executable symlinks...\")
 execute_process(
-- 
1.9.0

**Comment by pieper** [comment]
@ycollet - 

Thanks for the patch but it seems to have been truncated in the issue report.  Could you send a pull request intead?

Thx

**Comment by jcfr** [comment]
This has been fixed in 587b840a7828aec9a8165e875bcef8846000a881 and 7340be8ffc74d04f17531b62c7cdc3a32f6b539c

**Comment by pieper** [comment]
:+1:
