### ISSUE TITLE
Allow patch version to be configured

### ISSUE THREAD

**Issue by jcfr** [davidsansome/python-cmake-buildsystem#57]
Integrate changes from 00211c8 provided by @jrobcary

**Comment by jrobcary** [comment]
THanks!

John

**Comment by jcfr** [comment]
@jrobcary You contribution associated with a tweak of the continuous integration script and we have now have a build matrix for all version of python from `2.7.3` to `2.7.10`. :8ball: 

See https://open.cdash.org/index.php?project=CPython&date=2015-07-23#Travis-CI

Note that currently only topic starting with `ci-` prefix pushed on my fork (jcfr) are tested on travis and appveyor. This is because one of the original author of the build system gave me pull access to his repo (see #6  for more details about this) but i can't associate it with travis or appveyor. I guess at some point, we should probably transfer ownership of the project to a more visible location (most likely an organization to facilitate the administrative side of things - ideally the cpython organization on github). Before doing so ... I would like to have some basic support for python 3.x series and also setup testing of cross-compilation.

![cpython-build-matrix](https://cloud.githubusercontent.com/assets/219043/8843646/290ef078-30d9-11e5-944f-adc9b6e9a64b.png)

**Comment by jrobcary** [comment]
Very nice!

I have one more coming.
