### ISSUE TITLE
_socket.pyd not built under windows.

### ISSUE THREAD

**Issue by ycollet** [davidsansome/python-cmake-buildsystem#62]
_scoket.pyd is not built under windows.
I think this is due to the check of sys/socket.h which is a linux only system header (in ./cmake/ConfigureChecks.cmake)
Under windows, the header to check seems to be winsock2.h (included in some python source files).

**Comment by jcfr** [comment]
@ycollet After building python with shared library enabled, seems `_socket.pyd` is available. See attached screenshot.

Which CMake generator and build options are you using ?

![python-build-system_vs2008_socket](https://cloud.githubusercontent.com/assets/219043/9009133/0e83d378-376d-11e5-9d83-705caa9d6796.png)

**Comment by ycollet** [comment]
For the generator, I use "NMake Makefiles".
In fact _socket was compiled, but as a builtin. Not as a python module.
I added -DBUILTIN_SOCKET=OFF to my command line and now, I've got a _socket.pyd file.

**Comment by ycollet** [comment]
Arghhh ... My fault. I explicitely added a MSVC_BUILDTIN in the cmake source source.
Sorry for the noise, I close the bug.

**Comment by jcfr** [comment]
No problem :) Glad we figure the problem out.
